/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.io.File;
import javax.swing.JOptionPane;


/**
 *
 * @author anei
 */
public class Sokovision extends javax.swing.JFrame {
    
    private File selectedFile;

    /**
     * Creates new form EntryFrame
     */
    public Sokovision() {
        this.selectedFile = null;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        modeButtonGroup = new javax.swing.ButtonGroup();
        selectFileChooser = new javax.swing.JFileChooser();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        createNewProblemRButton = new javax.swing.JRadioButton();
        widthLabel = new javax.swing.JLabel();
        widthTextField = new javax.swing.JTextField();
        heightLabel = new javax.swing.JLabel();
        heightTextField = new javax.swing.JTextField();
        importProblemRButton = new javax.swing.JRadioButton();
        selectFileTextField = new javax.swing.JTextField();
        selectFileButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        okButton = new javax.swing.JButton();
        importProblemEditRButton = new javax.swing.JRadioButton();
        selectFileEditField = new javax.swing.JTextField();
        selectFileEditButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sokovision");
        setPreferredSize(new java.awt.Dimension(550, 320));
        setResizable(false);

        jPanel2.setPreferredSize(new java.awt.Dimension(550, 280));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setText("Choose operating mode:");

        modeButtonGroup.add(createNewProblemRButton);
        createNewProblemRButton.setText("create new problem");
        createNewProblemRButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createNewProblemRButtonActionPerformed(evt);
            }
        });

        widthLabel.setText("Width:");
        widthLabel.setEnabled(false);

        widthTextField.setEnabled(false);

        heightLabel.setText("Height:");
        heightLabel.setEnabled(false);

        heightTextField.setEnabled(false);

        modeButtonGroup.add(importProblemRButton);
        importProblemRButton.setText("import problem to solve");
        importProblemRButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importProblemRButtonActionPerformed(evt);
            }
        });

        selectFileTextField.setEnabled(false);

        selectFileButton.setText("Choose file");
        selectFileButton.setEnabled(false);
        selectFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectFileButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        modeButtonGroup.add(importProblemEditRButton);
        importProblemEditRButton.setText("import problem to edit");
        importProblemEditRButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importProblemEditRButtonActionPerformed(evt);
            }
        });

        selectFileEditField.setEnabled(false);

        selectFileEditButton.setText("Choose file");
        selectFileEditButton.setEnabled(false);
        selectFileEditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectFileButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(okButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelButton))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel1)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addGap(35, 35, 35)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(widthLabel)
                                .addComponent(heightLabel))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(heightTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                                .addComponent(widthTextField))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(selectFileEditField, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(selectFileEditButton, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(importProblemEditRButton)
                            .addComponent(createNewProblemRButton)
                            .addComponent(importProblemRButton)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(selectFileTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(selectFileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(createNewProblemRButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(widthLabel)
                    .addComponent(widthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(heightLabel)
                    .addComponent(heightTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(importProblemEditRButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectFileEditField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectFileEditButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(importProblemRButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectFileTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectFileButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(okButton))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    /*
        Action event handlers
    */
    private void createNewProblemRButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createNewProblemRButtonActionPerformed
        widthLabel.setEnabled(true);
        widthTextField.setEnabled(true);
        heightLabel.setEnabled(true);
        heightTextField.setEnabled(true);
        
        selectedFile = null;
        
        selectFileEditButton.setEnabled(false);
        selectFileEditField.setText("");
        
        selectFileButton.setEnabled(false);
        selectFileTextField.setText("");
    }//GEN-LAST:event_createNewProblemRButtonActionPerformed

    private void importProblemRButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importProblemRButtonActionPerformed
        widthLabel.setEnabled(false);
        widthTextField.setEnabled(false);
        heightLabel.setEnabled(false);
        heightTextField.setEnabled(false);
        
        selectedFile = null;
        
        selectFileEditButton.setEnabled(false);
        selectFileEditField.setText("");
        
        selectFileButton.setEnabled(true);
    }//GEN-LAST:event_importProblemRButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void selectFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectFileButtonActionPerformed
        int retVal = selectFileChooser.showOpenDialog(this);
        
        if (retVal == javax.swing.JFileChooser.APPROVE_OPTION) {
            selectedFile = selectFileChooser.getSelectedFile();
            
            if (!selectedFile.getName().endsWith(".skvi")) {
                selectedFile = null;
                selectFileTextField.setText("");
                JOptionPane.showMessageDialog(this, "Invalid file name extension. File name should end in '.skvi'.", "Warning", javax.swing.JOptionPane.WARNING_MESSAGE);
            } else {
                if (importProblemRButton.isSelected())
                    selectFileTextField.setText(selectedFile.getAbsolutePath());
                else if (importProblemEditRButton.isSelected())
                    selectFileEditField.setText(selectedFile.getAbsolutePath());
            }
        }
    }//GEN-LAST:event_selectFileButtonActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        // check which operating mode is selected
        if (createNewProblemRButton.isSelected()) {
            // create new problem
            // check if parameters are set
            if (!widthTextField.getText().equals("") && !heightTextField.getText().equals("")) {
                // check if input parameters are numbers
                try {
                    int width = Integer.parseInt(widthTextField.getText());
                    int height = Integer.parseInt(heightTextField.getText());
                    
                    this.setVisible(false);
                    new EditFrame(width, height).setVisible(true);
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(this, "Input parameters need to be numbers.", "Warning", javax.swing.JOptionPane.WARNING_MESSAGE);
                    widthTextField.setText("");
                    heightTextField.setText("");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Both width and height parameters must be set.", "Warning", javax.swing.JOptionPane.WARNING_MESSAGE);
            }
        } else if (importProblemRButton.isSelected()) {
            // solve mode
            if (selectedFile != null) {
                this.setVisible(false);
                new VisualFrame(selectedFile).setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "You must select a file to import from.", "Warning", javax.swing.JOptionPane.WARNING_MESSAGE);
            }
        } else if (importProblemEditRButton.isSelected()) {
            // import problem to editor
            if (selectedFile != null) {
                this.setVisible(false);
                EditFrame ef = new EditFrame(0, 0);
                ef.importFileToEdit(selectedFile);
                ef.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "You must select a file to import from.", "Warning", javax.swing.JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please choose operating mode.");
        }
    }//GEN-LAST:event_okButtonActionPerformed

    private void importProblemEditRButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importProblemEditRButtonActionPerformed
        widthLabel.setEnabled(false);
        widthTextField.setEnabled(false);
        heightLabel.setEnabled(false);
        heightTextField.setEnabled(false);
        
        selectedFile = null;
        
        selectFileEditButton.setEnabled(true);
        
        selectFileButton.setEnabled(false);
        selectFileTextField.setText("");
    }//GEN-LAST:event_importProblemEditRButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sokovision.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sokovision.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sokovision.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sokovision.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sokovision().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JRadioButton createNewProblemRButton;
    private javax.swing.JLabel heightLabel;
    private javax.swing.JTextField heightTextField;
    private javax.swing.JRadioButton importProblemEditRButton;
    private javax.swing.JRadioButton importProblemRButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.ButtonGroup modeButtonGroup;
    private javax.swing.JButton okButton;
    private javax.swing.JButton selectFileButton;
    private javax.swing.JFileChooser selectFileChooser;
    private javax.swing.JButton selectFileEditButton;
    private javax.swing.JTextField selectFileEditField;
    private javax.swing.JTextField selectFileTextField;
    private javax.swing.JLabel widthLabel;
    private javax.swing.JTextField widthTextField;
    // End of variables declaration//GEN-END:variables
}
